Repository skit-ai/skit-pipelines, pull requests merged in 2023-09, with the labels that each got.

#118 Add skeleton and basic validations for input parameters
  skit_pipelines/api/slack_bot.py
  skit_pipelines/api/validate_input.py
Labels: enhancement

#119 Delete deprecated pipelines from codebase
  skit_pipelines/components/__init__.py
  skit_pipelines/components/eevee_irr_with_yamls.py
  skit_pipelines/components/extract_info_from_dataset.py
  skit_pipelines/components/extract_tgz.py
  skit_pipelines/components/gen_confusion_matrix.py
  skit_pipelines/components/gen_eer_metrics.py
  skit_pipelines/components/gen_irr_metrics.py
  skit_pipelines/components/get_preds_voicebot_xlmr.py
  skit_pipelines/components/preprocess/create_features/__init__.py
  skit_pipelines/components/preprocess/create_features/utils.py
  skit_pipelines/components/preprocess/create_true_intent_column/__init__.py
  skit_pipelines/components/preprocess/create_true_intent_column/utils.py
  skit_pipelines/components/push_eer_to_postgres.py
  skit_pipelines/components/push_irr_to_postgres.py
  skit_pipelines/components/train_voicebot_xlmr.py
  skit_pipelines/components/upload2sheet/__init__.py
  skit_pipelines/pipelines/__init__.py
  skit_pipelines/pipelines/eer_from_tog/__init__.py
  skit_pipelines/pipelines/eval_voicebot_xlmr_pipeline/__init__.py
  skit_pipelines/pipelines/fetch_calls_n_push_to_sheets/__init__.py
  skit_pipelines/pipelines/fetch_calls_n_upload_tog_and_sheet/__init__.py
  skit_pipelines/pipelines/irr_from_tog/__init__.py
  skit_pipelines/pipelines/train_voicebot_intent_model_xlmr/__init__.py
Labels: Pipeline

#121 Add comparision confusion matrix between trained model and production
  skit_pipelines/components/create_mr.py
  skit_pipelines/components/retrain_slu_from_repo/__init__.py
  skit_pipelines/components/retrain_slu_from_repo/comparision_report_generator.py
  skit_pipelines/components/retrain_slu_from_repo/utils.py
  skit_pipelines/pipelines/retrain_slu/__init__.py
Labels: enhancement

#120 Write DVC configs when pushing new SLU model
  skit_pipelines/components/retrain_slu_from_repo/__init__.py
Labels: bug

#122 Delete lock file
  skit_pipelines/components/retrain_slu_from_repo/__init__.py
Labels: bug

#123 Minor update kfp
  poetry.lock
  pyproject.toml
  skit_pipelines/components/fetch_calls.py
Labels: Integrations
